#!/bin/sh
echo "Running pre-commit checks..."
echo "1. Running format on staged files..."
bunx lint-staged --verbose | grep "prettier" || exit 1

echo "2. Running lint on staged files..."
bunx lint-staged --verbose | grep "eslint" || exit 1

echo "All pre-commit checks passed! 🎉"
